# Generated by Django 4.2.4 on 2023-09-03 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=100)),
                ('national_id', models.BigIntegerField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='classManagement.courses')),
            ],
        ),
    ]
