from django.urls import path
from .views import (
    HomeTemplateView,
    CoursesListView,
    CourseDetailView,
    ArticleCreateView,
    ArticleListView,
    ArticleUpdateView,
    ArticleDeleteView,
    ArticleDetailView,
    DayPresentDetailView,
    PresentUpdateView,
    CourseDateListView,
    FileDetailView,
    FileCreateView,
    FileListView,
    FileUpdateView,
    FileDeleteView,
    PdfStudentListView,
    StudentListView,
    TestTemplateView,
    TestListView,
    TestDetailView,
    ResultUpdateView
)

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('coursesList/', CoursesListView.as_view(), name='courses_list'),
    path('courseDetail/<uuid:pk>', CourseDetailView.as_view(), name='course_detail'),
    path('createArticle/', ArticleCreateView.as_view(), name="article_create"),
    path('articlesList/<uuid:pk>/articles', ArticleListView.as_view(), name='article_list'),
    path('articleUpdate/<uuid:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('articleDelete/<uuid:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
    path('articleDetail/<uuid:pk>', ArticleDetailView.as_view(), name='article_detail'),
    path('present/dayDetail/<uuid:pk>', DayPresentDetailView.as_view(), name='day_detail'),
    path('presentUpdate/<uuid:pk>/update/', PresentUpdateView.as_view(), name='present_update'),
    path('courseDateList/', CourseDateListView.as_view(), name='course_date_list'),
    path('fileView/<uuid:pk>', FileDetailView.as_view(), name='file_view'),
    path('fileCreate/', FileCreateView.as_view(), name='file_create'),
    path('fileList/<uuid:pk>/files', FileListView.as_view(), name='file_list'),
    path('fileUpdate/<int:pk>/update/', FileUpdateView.as_view(), name='file_update'),
    path('fileDelete/<int:pk>/delete/', FileDeleteView.as_view(), name='file_delete'),
    path('studentList/<uuid:pk>/studentslist', PdfStudentListView.as_view(), name='student_list'),
    path('studentList/<uuid:pk>/students', StudentListView.as_view(), name='student_list_view'),
    path('TestView/<uuid:pk>', TestTemplateView.as_view(), name='test_view'),
    path('testList/<uuid:pk>/tests', TestListView.as_view(), name='test_list'),
    path('testDetail/<uuid:pk>/detail/', TestDetailView.as_view(), name='test_detail'),
    path('resultUpdate/<uuid:pk>/update/', ResultUpdateView.as_view(), name='result_update')
]
